name: Create a new version

on:
  push

jobs:
  version:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
                
      - name: Inital Test
        run: echo Hello, world!

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
            node-version: '14.x'
      - run: npm install
      - run: npm test