name: Create a new version

on:
    push

jobs:
    version:
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install dependenices
              run: npm ci

            - name: Set up git
              run: |
                git fetch
                git checkout master
                git config user.name botify
            - name: Checkout new branch
              run: git checkout -b version-bump-${{ github.sha }}