name: Create a new version

on:
  push

jobs:
  version:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        
        
      - name: Inital Test
        run: echo Hello, world!
